

C = g++
CCFLAGS = -Wall  -g
REQUERIMIENTOS= cpp/DataTypes/Mensaje/DtContacto.cpp cpp/DataTypes/Mensaje/DtImagen.cpp cpp/DataTypes/Mensaje/DtMensaje.cpp \
cpp/DataTypes/Mensaje/DtSimple.cpp cpp/DataTypes/Mensaje/DtVideo.cpp cpp/DataTypes/Dt cpp/DataTypes/DtConversacion.cpp \
cpp/DataTypes/DtContacto.cpp cpp/DataTypes/DtInfoIngreso.cpp cpp/DataTypes/DtNotificacion.cpp cpp/DataTypes/DtReceptor.cpp \
cpp/Simple/Mensaje/Mensaje.cpp cpp/Simple/Mensaje/Contacto.cpp cpp/Simple/Mensaje/Imagen.cpp cpp/Simple/Mensaje/Simple.cpp \
cpp/Simple/Mensaje/Video.cpp cpp/Simple/Conversacion.cpp cpp/Simple/EstadoConversacion.cpp cpp/Simple/Fecha.cpp \
cpp/Simple/FechaSistema.cpp cpp/Simple/Grupo.cpp cpp/Simple/Hora.cpp cpp/Simple/HoraSistema.cpp cpp/Simple/InfoIngreso.cpp \
cpp/Simple/Recibido.cpp cpp/Simple/Usuario.cpp cpp/Controllers/CtrlCasoEnviar.cpp cpp/Controllers/CtrlUsuario.cpp main.cpp
main: $(REQUERIMIENTOS)
	 $(C) $(CCFLAGS) $(REQUERIMIENTOS) -o main 

    
